### ISSUE TITLE
shortage EXCC

### ISSUE THREAD

**Issue by Specc-2** [EXCCoin/exilibrium#19]
When transferring from an old wallet to a new one, the part of EXCC was lost. 
was 12371 became the 4135 EXCC ? 
Screen of both wallets 2018-08-31_214838.jpg 
![2018-08-31_214838](https://user-images.githubusercontent.com/42869995/44922703-e7faa500-ad67-11e8-8efe-047e9c32df18.jpg)

The value of the GAP was set at 22/200/499/500/1000/5000/10000/100000. I save and then scan the blockchain, there are no changes.
Exilibrium updated to beta 7., I change the value of GAP again, there are no changes.
I activate the wallet with 12words. and using the purse export file. always 4135 ЕХСС and does not change to 12371 ЕХСС. 
Please, restore EXCC.
There is a file with the history of transactions of the old wallet (.csv format)
if need I can send.

**Comment by jwjanus** [comment]
Hi, apologies for long response time. Usually in such cases increasing the gap limit & rescanning should do the thing. I'll consult your issue with the rest of the team and let you know what to do next. Thanks for comprehensive issue description.

**Comment by jwjanus** [comment]
Ok, we investigated the issue a bit. Can you please check your account balance at Coin Exchange?

**Comment by Specc-2** [comment]
The bulk of transfers between the exchanges TOPBTC and CoinEnchange.
Screenshots and lists of stories.
https://www.dropbox.com/sh/otvav0s17bd7vha/AAA1l_EOypC5NCqIvm50ZS8Ba?dl=0
Tell me if you need more information.
(I'll delete the link later.)

**Comment by jwjanus** [comment]
Got it. You can remove the link. I'll get back to you in 12-15 hours.

**Comment by jwjanus** [comment]
Did some research in your case. It seems that all balances (those that i found) on addresses used in transactions in the old wallet are kept intact from the start of the new blockchain. They're included in the first, premined block and are unspent. Could you paste each of addresses listed below in "Security" > "Validate address" section in  Exilibrium?

22u8zZu5hKyrBtEMXpshj1UpC4atP4zigdGr
22tuKsyksaAZUBt3BM8gRBaLTqz8pSV7y2Gu
22tyPJF5bxasNKeiso22Vb3UuQPZtGJLXLhf
22tz9Tk87oE8Ui71VuaEBiPk1Vhixf6pAipw
22u5odhaHdPPbQkM9w8MrM6HJqJduf2ovXMq
22u39bxiiKcbRaNj3KuzB2dSiPkdYgLLuj5B
22tt7GRdUxJxTLeJeNPDbDKCCYuYFni759Lq
22txpiwp2qjq4rpEBiQCWznFvMFS7tC6Cbtd
22u52oKAPiaLnowhR7R6PZGb3KnfaibcCrj6
22tvDVsyaNrcHgxzS7VJwvtsUg6oNeNbaL6r
22touwsoDr4KbMLdsAeBFMswnDChyBLDREbY
22u2ga8PVuBXsgWT1T4jSZjMAyBTH7Tt6KHi 
22tv5taaRyuXUWygeLMCvGi9nQgmznqKLFmc

For every one of these it should tell you that this address is owned.

**Comment by Specc-2** [comment]
Screenshots and address lists.
https://www.dropbox.com/sh/ixs8x5imozud5xd/AAAVDjifaoVGvJlneoJNzMGpa?dl=0
The total balance from "Not owned address!" almost coincides with the shortage.
You are on the right track.

**Comment by jwjanus** [comment]
Cool, thanks for checking. You can delete dropbox link. I'll investigate the issue further in approx 12 hours.

**Comment by jwjanus** [comment]
We probably found a solution. Unfortunately it seems that there is a bug in Exilibrium, but there is a way of bypassing it until a new version is released. 
I see that you're using Windows, so you need to go to this path:
`C:\Users\<your-username>\AppData\Local\Exilibrium\wallets\mainnet\<your-wallet-name>\`
In this directory there should be a file called `exccwallet.conf`, all you need to do is add a new line (probably it would be below `nolegacyrpc=1` option) with `gaplimit=<some number>` (for example `gaplimit=500`). 
You could try multiple times with increasing numbers, eg. 100 -> 1000 -> 10000 until it finds all your missing funds. Remember that after exccwallet config file has been changed whole app should be restarted to load new options. 
Sorry for the inconvenience, please let us know here if your issue was resolved.

**Comment by Specc-2** [comment]
Yes, it helped.
Thank you, great work.
![2018-09-05_220928](https://user-images.githubusercontent.com/42869995/45109261-d860cf00-b160-11e8-8cce-fe998ae43dc7.jpg)
The question: a new line to remove? or leave (for example <gaplimit=20>).

**Comment by jwjanus** [comment]
That's great :+1: In order to restore default gaplimit setting and still have all funds discovered you'd need to transfer the funds from old addresses to the new ones. The easiest way to do this, using the same wallet, could be done as follows:
- Go to "Transactions" -> "Receive"
- Copy receive address
- Go to "Transactions" -> "Send" tab
- Choose "default" account in "From" account (should be selected by default)
- Click on "Send all funds from selected account" - icon on the right
- Paste the address and click "Send" (this will create new transaction on the blockchain)
Newly generated addresses will work fine with default gaplimit setting.
It could happen that you'll get an error because transaction size would exceed the limit - then there is another option, but it's not that easy to describe.

**Comment by Specc-2** [comment]
Everything went well.
Thank you very much.
Please close this question.
